### ISSUE TITLE
Veranstaltung: Essential Info This will show on the event home page funktioniert nicht

### ISSUE THREAD

**Issue by 4ipalino** [Apfelwurm/eventula-manager#15]
Es wird immer die lange Version angezeigt

**Comment by Apfelwurm** [comment]
fixed in https://github.com/Apfelwurm/eventula-manager/commit/576d5bac0171c8b912f999c9035de65b065dce75 and https://github.com/Apfelwurm/eventula-manager/commit/ea8f4b15ea08ec32ddc58d98dd375824397946db
