### ISSUE TITLE
Get5 System2 conector 

### ISSUE THREAD

**Issue by Apfelwurm** [Apfelwurm/eventula-manager#22]
Get5 System2 conector

**Comment by Apfelwurm** [comment]
https://github.com/dordnung/System2

**Comment by 4ipalino** [comment]
https://github.com/splewis/get5/blob/b19524ebb354d0c887e2fed3da5a5859bce5191d/scripting/get5/matchconfig.sp#L211

Steamworks kann https.
Aber der ersetzt http durch https -.-

**Comment by Apfelwurm** [comment]
> https://github.com/splewis/get5/blob/b19524ebb354d0c887e2fed3da5a5859bce5191d/scripting/get5/matchconfig.sp#L211
> 
> Steamworks kann https.
> Aber der ersetzt http durch https -.-

lol...

**Comment by Apfelwurm** [comment]
erledigt durch PR in get5
