### ISSUE TITLE
Regeln für das Turnier (z.B. wie gehen wir mit Teams um bei denen jemand fehlt, wie sieht es bei Verbindungsproblemen einzelner Spieler aus, ...)

### ISSUE THREAD

**Issue by 4ipalino** [Apfelwurm/eventula-manager#4]

**Comment by Apfelwurm** [comment]
erledigt außer:

Befehle (TODO)
.ready

.pause

...



Spielablauf (TODO)


Mit Spiel verbinden
Mapauswahl
Mapchange
Kniferound
Side choice
Pauses
End of Game

**Comment by Apfelwurm** [comment]
Verifizieren!
